### ISSUE TITLE
Where is './Dataset/trainset/rgb_clean_patches.npy" ??

### ISSUE THREAD

**Issue by edwardcho** [Magauiya/Extended_SURE#1]
Hello Sir,

Because I need denoising function, I found your git-hub site.
At first, I tested your source code using your data-set.

1. Patch generation for training
  a. python2 generate_patches_rgb_gt.py   -> this command ran normally.
  b. python2 generate_patches_rgb_noisy.py --std_imp_min=5. --std_imp_max=10. --std_noisy_max=55.   -> I met some error.

'''
FileNotFoundError: [Errno 2] No such file or directory: './Dataset/trainset/rgb_clean_patches.npy'
'''
How can generate this file?? or Where is this file??

**Comment by Magauiya** [comment]
Hi Edward,

Firstly, you need to generate clean patches by running 

`python2 generate_patches_rgb_gt.py`

It will save generated patches in /Dataset/trainset/

Then you can run:
`python2 generate_patches_rgb_noisy.py --std_imp_min=5. --std_imp_max=10. --std_noisy_max=55.`

**Comment by Magauiya** [comment]
> Hello Sir,
> 
> Because I need denoising function, I found your git-hub site.
> At first, I tested your source code using your data-set.
> 
> 1. Patch generation for training
>    a. python2 generate_patches_rgb_gt.py   -> this command ran normally.
>    b. python2 generate_patches_rgb_noisy.py --std_imp_min=5. --std_imp_max=10. --std_noisy_max=55.   -> I met some error.
> 
> '''
> FileNotFoundError: [Errno 2] No such file or directory: './Dataset/trainset/rgb_clean_patches.npy'
> '''
> How can generate this file?? or Where is this file??

Hi Edward,

Firstly, you need to generate clean patches by running 

`python2 generate_patches_rgb_gt.py`

It will save generated patches in /Dataset/trainset/

Then you can run:
`python2 generate_patches_rgb_noisy.py --std_imp_min=5. --std_imp_max=10. --std_noisy_max=55.`

**Comment by edwardcho** [comment]
I found some weird code at generate_patches_rgb_gt.py.
I modified this code.

# original code
...
np.save(args.save_dir, inputs)
...

# changed code
...
npy_filename = 'rgb_clean_patches'
np.save(os.path.join(args.save_dir, npy_filename), inputs)
'''

After changed this code, my code can process.
