### ISSUE TITLE
FileNotFoundError ??

### ISSUE THREAD

**Issue by edwardcho** [Magauiya/Extended_SURE#2]
Hello Sir,

I tested your code but I met some error.

After generate this files using 'generate_patches_rgb_noisy.py",
    rgb_noisy_5_patches.npy
   sigma_rgb_vector_blind_5.npy

I ran "python main_blind_rgb.py -- phase train --sigma 10 --cost=e-SURE --type=5 --test_set=CBSD58", I saw this error message.

FileNotFoundError: [Errno 2] No such file or directory: './Dataset/trainset/sigma_rgb_vector_blind_5_10.npy'

As you know, generated filename of sigma_rgb_vector_blind_x.py(sigma_rgb_vector_blind_5.npy) included gt_type only,
How do I generate new filename that includes sigma parameter.
(sigma_rgb_vector_blind_5_10.npy)

Thanks.

**Comment by Magauiya** [comment]
> Hello Sir,
> 
> I tested your code but I met some error.
> 
> After generate this files using 'generate_patches_rgb_noisy.py",
> rgb_noisy_5_patches.npy
> sigma_rgb_vector_blind_5.npy
> 
> I ran "python main_blind_rgb.py -- phase train --sigma 10 --cost=e-SURE --type=5 --test_set=CBSD58", I saw this error message.
> 
> FileNotFoundError: [Errno 2] No such file or directory: './Dataset/trainset/sigma_rgb_vector_blind_5_10.npy'
> 
> As you know, generated filename of sigma_rgb_vector_blind_x.py(sigma_rgb_vector_blind_5.npy) included gt_type only,
> How do I generate new filename that includes sigma parameter.
> (sigma_rgb_vector_blind_5_10.npy)
> 
> Thanks.

Hi! 

Files are correctly generated, but naming is not correct. So, I will fix it by today. Thank you for your patient.

**Comment by edwardcho** [comment]
Hello Sir,

Thanks.
