### ISSUE TITLE
whether sigma need to divide 255 to compute epsilon

### ISSUE THREAD

**Issue by ShireLiuSZ** [Magauiya/Extended_SURE#4]
The paper showed epsilon should be 1.6 * sigma * 1e-4. In the code, the input has been normalized between 0 and 1, but the sigma used to compute epsilon still corresponded to the input between 0 and 255, such as 25.  
So I want to confirm whether the sigma used to compute epsilon need to divide 255 to match the input between 0 and 1. Thanks for your reply.

**Comment by Magauiya** [comment]
> The paper showed epsilon should be 1.6 * sigma * 1e-4. In the code, the input has been normalized between 0 and 1, but the sigma used to compute epsilon still corresponded to the input between 0 and 255, such as 25.
> So I want to confirm whether the sigma used to compute epsilon need to divide 255 to match the input between 0 and 1. Thanks for your reply.

Sigma should be between 0-255 to estimate epsilon, although the image range is [0-1].

**Comment by ShireLiuSZ** [comment]
Thank you very much!
